//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class товары_
    {
        public long id { get; set; }
        public string Артикул { get; set; }
        public string Наименование { get; set; }
        public string Единица_измерения { get; set; }
        public Nullable<decimal> Стоимость { get; set; }
        public Nullable<int> Размер_максимально_возможной_скидки { get; set; }
        public string Производитель { get; set; }
        public string Поставщик { get; set; }
        public string Категория_товара { get; set; }
        public Nullable<int> Действующая_скидка { get; set; }
        public Nullable<int> Количество_на_складе { get; set; }
        public string Описание { get; set; }
        public string Изображение { get; set; }
    }
}
